### ISSUE TITLE
Error getting container IP from Docker API

### ISSUE THREAD

**Issue by iromli** [GluuFederation/docker-cr-rotate#4]
The following error is thrown during retrieval of container IP:

```python
Traceback (most recent call last):
  File "/opt/cr-rotate/scripts/cr_rotating_de.py", line 270, in <module>
    main()
  File "/opt/cr-rotate/scripts/cr_rotating_de.py", line 195, in main
    [first_default_network_name]['IPAddress'].strip()
TypeError: list indices must be integers, not str
```

**Comment by mogluu** [comment]
Changed method to container.attrs.
